name: Backend CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build and test
        working-directory: Project/flight-aggregator-app/backend/aggregator-service
        run: |
          chmod +x ./gradlew
          ./gradlew build
